version: '3.8'

services:
  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ishimwejeanluc/portfolio-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Lukatoni123
      - DB_NAME=portofolio
      - DB_PORT=3306
    networks:
      - portfolio-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`portfolio.auca.ac.rw`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=3000"


  # MySQL database with data persistence
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Lukatoni123
      - MYSQL_DATABASE=portofolio
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - portfolio-network
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  mysql_data:

networks:
  portfolio-network:
    driver: overlay
      context: .
      dockerfile: Dockerfile.mysql
    image: ishimwejeanluc/portfolio-mysql:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=Lukatoni123
      - MYSQL_DATABASE=portofolio
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - portfolio-network

  # Traefik as reverse proxy and load balancer
  traefik:
    image: traefik:v2.9
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "8080:8080"  # Dashboard (secure this in production)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    networks:
      - portfolio-network
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"  # In production, secure the dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=ishimwe.luc@auca.ac.rw"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"

networks:
  portfolio-network:
    driver: overlay
    attachable: true

volumes:
  mysql-data:
    driver: local
