api:
  dashboard: true
  insecure: true  # For development only, set to false in production

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "ishimwe.luc@auca.ac.rw"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web

# Enable access logs
accessLog: {}

# Enable Traefik logs
log:
  level: INFO
